# https://www.dartlang.org/guides/language/analysis-options
# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
analyzer:
#    implicit-casts: false
#    implicit-dynamic: false
  errors:
    todo: ignore
  exclude:
    - flutter/**
    - lib/*.dart

linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
